# Generated by go2rpm 1.17.1
%bcond check 1

# https://github.com/netbirdio/netbird
%global goipath         github.com/netbirdio/netbird
Version:                0.56.1

%gometa -L -f


Name:           netbird
Release:        %autorelease
Summary:        Connect your devices into a secure WireGuard®-based overlay network with SSO, MFA and granular access controls

# Generated by go-vendor-tools
License:        AGPL-3.0-only AND Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND CC0-1.0 AND GPL-3.0-only AND ISC AND MIT AND MPL-2.0 AND Unlicense AND Zlib AND (BSD-3-Clause OR Unlicense)
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

BuildRequires:  go-vendor-tools, libX11-devel, libXcursor-devel, libXrandr-devel, libglvnd-devel, libXinerama-devel, libXi-devel, libXxf86vm-devel

%description
Connect your devices into a secure WireGuard®-based overlay network with SSO,
MFA and granular access controls.

%prep
%goprep -A
%setup -q -T -D -a1 %{forgesetupargs}
# autopatch -p1

%generate_buildrequires
%go_vendor_license_buildrequires -c %{SOURCE2}

%build
%global gomodulesmode GO111MODULE=on
for cmd in client client/ui; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%go_vendor_license_install -c %{SOURCE2}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/client %{buildroot}%{_bindir}/netbird
install -m 0755 -vp %{gobuilddir}/bin/ui %{buildroot}%{_bindir}/netbird-ui

%check
#%go_vendor_license_check -c %{SOURCE2}

%files -f %{go_vendor_license_filelist}
%license vendor/modules.txt
%doc docs AUTHORS CODE_OF_CONDUCT.md CONTRIBUTING.md
%doc CONTRIBUTOR_LICENSE_AGREEMENT.md README.md SECURITY.md
%doc client/iface/mocks/README.md
%doc infrastructure_files/observability/grafana/dashboards/readme.md
%doc management/README.md example signal/README.md
%{_bindir}/netbird
%{_bindir}/netbird-ui

%changelog
%autochangelog
