# disable debuginfo packages
%global debug_package %{nil}

# Generated by go2rpm 1.17.1
%bcond check 1

# Set --with bundle_vendored to bundle vendored sources into tarballs
%bcond bundle_vendored 0
# Set --with bundle_vendored_force to overwrite existing archive files
%bcond bundle_vendored_force 0

# https://github.com/netbirdio/netbird
%global goipath         github.com/netbirdio/netbird
%global netbirdversion  0.73.2
Version:                %{netbirdversion}

%gometa -L -f

# SELinux policy type
%global selinuxtype targeted

Name:           netbird
Release:        %autorelease
Summary:        Connect your devices into a secure WireGuard®-based overlay network with SSO, MFA and granular access controls

# Generated by go-vendor-tools
License:        AGPL-3.0-only AND Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND CC0-1.0 AND GPL-3.0-only AND ISC AND MIT AND MPL-2.0 AND Unlicense AND Zlib AND (BSD-3-Clause OR Unlicense)
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml
Source3:        netbird.service
Source4:        client_config.json

# Netbird UI user systemd service
Source5:        netbirdui.service

# Configure logrotate to rotate client log
Source6:        netbird.logrotate

# SELinux policy files
Source7:        netbird.te
Source8:        netbird.fc
Source9:        netbird.if

# Local updates
## Disable the update client check for Fedora package
Patch01:        Disable-client-version-update-for-Fedora-package.patch

BuildRequires:  go-vendor-tools
BuildRequires:  selinux-policy-devel
BuildRequires:  libX11-devel, libXcursor-devel, libXrandr-devel, libglvnd-devel, libXinerama-devel, libXi-devel, libXxf86vm-devel
BuildRequires:  systemd-rpm-macros
# for hardlinks executable
BuildRequires:  util-linux-core

%description
Connect your devices into a secure WireGuard-based overlay network with SSO,
MFA and granular access controls.

%package client
Summary: The netbird client command line tool and systemd service
Requires: %{name} = %{version}-%{release}
Requires: (%{name}-selinux = %{version}-%{release} if selinux-policy-targeted)

%description client
The netbird client includes the 'netbird' command line tool as well as
systemd services that the command line tool interacts with to run
the service.

%package ui
Summary: The graphical netbird interface
Requires: %{name} = %{version}-%{release}
Requires: %{name}-client = %{version}-%{release}

%description ui
The graphical client used to run and manage your netbird connection.

%package selinux
Summary: SELinux policy module for netbird
BuildArch: noarch
Requires: %{name}-client = %{version}-%{release}
Requires: selinux-policy-base >= %{_selinux_policy_version}
Requires(post): selinux-policy-base >= %{_selinux_policy_version}
Requires(post): policycoreutils
Requires(post): libselinux-utils
%{?selinux_requires}

%description selinux
SELinux policy module for netbird. This package provides the SELinux policy
required for netbird to manage network interfaces, modify DNS configuration,
and perform other VPN-related operations.

%prep
%goprep -A
%setup -q -T -D -a1 %{forgesetupargs}
%autopatch -p1

# Copy SELinux policy files to build directory
cp %{SOURCE7} %{SOURCE8} %{SOURCE9} .

%generate_buildrequires
%go_vendor_license_buildrequires -c %{SOURCE2}

%build
%global gomodulesmode GO111MODULE=on
# LD Flags stolen from the upstream vendor's build command, changed to say
# that it was built by Red Hat IT
LDFLAGS="-s -w -X github.com/netbirdio/netbird/version.version=%{version} -X main.commit=v%{netbirdversion} -X main.builtBy=redhatit"
for cmd in client client/ui; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

# Copy the client config into the build directory
cp %{SOURCE4} .

# Build SELinux policy module
make -f /usr/share/selinux/devel/Makefile netbird.pp
bzip2 -9 netbird.pp

%install
%go_vendor_license_install -c %{SOURCE2}
install -m 0755 -vd %{buildroot}%{_bindir}

install -m 0755 -vp %{gobuilddir}/bin/client %{buildroot}%{_bindir}/netbird
install -m 0755 -vp %{gobuilddir}/bin/ui %{buildroot}%{_bindir}/netbird-ui

# desktop client tools
install -m 0755 -vd %{buildroot}%{_datarootdir}/applications
install -m 0755 -vd %{buildroot}%{_datarootdir}/icons
install -m 0755 -vp client/ui/build/netbird.desktop %{buildroot}%{_datarootdir}/applications/netbird.desktop
install -m 0755 -vp client/ui/assets/netbird.png %{buildroot}%{_datarootdir}/icons/netbird.png
install -m 0644 -vD %{SOURCE5} %{buildroot}%{_userunitdir}/netbirdui.service

# systemd service
install -m 0755 -vd %{buildroot}%{_unitdir}
install -m 0644 -vp %{SOURCE3} %{buildroot}%{_unitdir}/netbird.service
install -m 0755 -vd %{buildroot}%{_sharedstatedir}/netbird

# log directory
install -m 0744 -vd %{buildroot}%{_localstatedir}/log/netbird
install -m 0644 -vD %{SOURCE6} %{buildroot}%{_sysconfdir}/logrotate.d/netbird

# client configration
install -m 0755 -vd %{buildroot}%{_sysconfdir}/netbird

# SELinux policy module
install -m 0755 -vd %{buildroot}%{_datadir}/selinux/packages
install -m 0644 -vp netbird.pp.bz2 %{buildroot}%{_datadir}/selinux/packages/

# Create hard links for all the duplicate license files
hardlink --ignore-time %{buildroot}


%check
%go_vendor_license_check -c %{SOURCE2}


%post client
%systemd_post netbird.service

%preun client
%systemd_preun netbird.service

%postun client
%systemd_postun_with_restart netbird.service

%post ui
%systemd_user_post netbirdui.service

%preun ui
%systemd_user_preun netbirdui.service

%postun ui
%systemd_user_postun_with_restart netbirdui.service
%systemd_user_postun_with_reload netbirdui.service
%systemd_user_postun netbirdui.service

%pre selinux
%selinux_relabel_pre -s %{selinuxtype}

%post selinux
%selinux_modules_install -s %{selinuxtype} %{_datadir}/selinux/packages/netbird.pp.bz2
if [ $1 -eq 1 ]; then
    # First installation - restore file contexts
    restorecon -R %{_bindir}/netbird 2>/dev/null || :
    restorecon -R %{_sysconfdir}/netbird 2>/dev/null || :
    restorecon -R %{_sharedstatedir}/netbird 2>/dev/null || :
    restorecon -R %{_localstatedir}/log/netbird 2>/dev/null || :
    restorecon -F %{_rundir}/netbird.sock 2>/dev/null || :
fi

%postun selinux
if [ $1 -eq 0 ]; then
    # Complete removal
    %selinux_modules_uninstall -s %{selinuxtype} netbird
fi

%posttrans selinux
%selinux_relabel_post -s %{selinuxtype}

%files -f %{go_vendor_license_filelist}
%license vendor/modules.txt
%doc docs AUTHORS CODE_OF_CONDUCT.md CONTRIBUTING.md
%doc CONTRIBUTOR_LICENSE_AGREEMENT.md README.md SECURITY.md
%doc client_config.json

%files client
%{_bindir}/netbird
%{_unitdir}/netbird.service
%dir %{_sysconfdir}/netbird
%attr(0755, root, root) %dir %{_sharedstatedir}/netbird
%ghost %config(noreplace) %{_sysconfdir}/netbird/config.json
%ghost %config(noreplace) %{_sharedstatedir}/netbird/active_profile.json
%ghost %config(noreplace) %{_sharedstatedir}/netbird/state.json
%attr(0744, root, root) %dir %{_localstatedir}/log/netbird
%ghost %{_localstatedir}/log/netbird/client.log
%{_sysconfdir}/logrotate.d/netbird
%ghost %{_rundir}/netbird.sock

%files ui
%{_bindir}/netbird-ui
%{_datarootdir}/applications/netbird.desktop
%{_datarootdir}/icons/netbird.png
%{_userunitdir}/netbirdui.service

%files selinux
%{_datadir}/selinux/packages/netbird.pp.bz2
%ghost %{_sharedstatedir}/selinux/%{selinuxtype}/active/modules/200/netbird

%changelog
%autochangelog
